### ISSUE TITLE
uncaughtException: Cannot read property 'contents' of undefined   at Object.Parser.parse 

### ISSUE THREAD

**Issue by chandanpasunoori** [inventures/hatchjs#13]
```
GET /do/stylesheet/css/0 controller: stylesheet action: css
Params: {"version":"0"}
>>> perform css
MULTI
  GET dev/User:1
  EVALSHA [Lua: ZRANGE+MGET] 0 z:dev/Page:url:localhost:3000 0 0 dev/Page
EXEC [41 ms]
EVALSHA [Lua: ZRANGE+MGET] 0 z:dev/Stylesheet:groupId:1 0 0 dev/Stylesheet [0 ms]
Stylesheet: not found. Setting default theme
uncaughtException
uncaughtException: Cannot read property 'contents' of undefined
  at Object.Parser.parse (/home/user/Workspace/NodeProjects/Hatch/node_modules/less/lib/less/parser/parser.js:108:20)
  at /home/user/Workspace/NodeProjects/Hatch/app/models/Stylesheet.js:118:20
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/async/lib/async.js:119:25
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/async/lib/async.js:24:16
  at /home/user/Workspace/NodeProjects/Hatch/app/models/Stylesheet.js:104:21
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:81:16
  at Object.oncomplete (fs.js:107:15)

Notify error
uncaughtException: Cannot read property 'contents' of undefined
  at Object.Parser.parse (/home/user/Workspace/NodeProjects/Hatch/node_modules/less/lib/less/parser/parser.js:108:20)
  at /home/user/Workspace/NodeProjects/Hatch/app/models/Stylesheet.js:118:20
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/async/lib/async.js:119:25
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/async/lib/async.js:24:16
  at /home/user/Workspace/NodeProjects/Hatch/app/models/Stylesheet.js:104:21
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:71:17
  at /home/user/Workspace/NodeProjects/Hatch/node_modules/file-finder/file-finder.js:81:16
  at Object.oncomplete (fs.js:107:15)

user@system:~/Workspace/NodeProjects/Hatch$ 

```

**Comment by RoseAsbenhe** [comment]
Got the same problem as i tried to start my application. I really wanted to try out hatch.js (my last project was with keystone.js) but I can't continue to work.
