### ISSUE TITLE
Broken Dependencies

### ISSUE THREAD

**Issue by ub1quit33** [inventures/hatchjs#15]
It would appear that hatch.js does not work with the latest version of file-finder.

```node
Stylesheet: not found. Setting default theme
uncaughtException
uncaughtException: Cannot read property 'contents' of undefined
  at Object.Parser.parse (/home/james/node_modules/hatchjs/node_modules/less/lib/less/parser/parser.js:117:20)
  at /home/james/node_modules/hatchjs/app/models/Stylesheet.js:118:20
  at /home/james/node_modules/hatchjs/node_modules/async/lib/async.js:119:25
  at /home/james/node_modules/hatchjs/node_modules/async/lib/async.js:24:16
  at /home/james/node_modules/hatchjs/app/models/Stylesheet.js:104:21
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:81:16
  at FSReqWrap.oncomplete (fs.js:95:15)

Notify error
uncaughtException: Cannot read property 'contents' of undefined
  at Object.Parser.parse (/home/james/node_modules/hatchjs/node_modules/less/lib/less/parser/parser.js:117:20)
  at /home/james/node_modules/hatchjs/app/models/Stylesheet.js:118:20
  at /home/james/node_modules/hatchjs/node_modules/async/lib/async.js:119:25
  at /home/james/node_modules/hatchjs/node_modules/async/lib/async.js:24:16
  at /home/james/node_modules/hatchjs/app/models/Stylesheet.js:104:21
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:81:16
  at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by ub1quit33** [comment]
Actually it looks like file-finder is the broken piece here... I'll raise the issue with their project

**Comment by ub1quit33** [comment]
This is probably not an issue with file-finder, per [the response of that maintainer](https://github.com/ZECTBynmo/file-finder/issues/3#issuecomment-97818428). It seems like this is a hatchjs issue. For anyone who discovers this issue through Google or whatnot, I worked around this by installing an older version of less, but I afterward encountered other weird issues while experimenting with hatch.js.

It seems like this project is no longer maintained, so it's probably best to just find another platform to use.
